### ISSUE TITLE
Could not find function "stopifnotlas" in lastree

### ISSUE THREAD

**Issue by Indu-cherukuri** [Jean-Romain/lidR#122]
> lastrees(lasnorm, "watershed", chm, th = 4,extra=T) 
Error in stopifnotlas(las) : could not find function "stopifnotlas"

**Comment by Jean-Romain** [comment]
Which version are you using? Did you installed it from CRAN? What is your operating system? I swear that `stopifnotlas` exists otherwise there are not a lot of functions that could  not work. I just tested it and i confirm it works. 

Maybe something went wrong during the installation. You may try to reinstall the package..

**Comment by Indu-cherukuri** [comment]
Hi, Thanks for the quick revert. My operating system is Linux Mint. I installed it using install.packages("lidR") in RStudio from CRAN. I tried uninstalling the package and installing it again, but it didn't help. I am unable to figure out the issue.

**Comment by Jean-Romain** [comment]
Well, I really embarrassed for you. I cannot reproduce this issue (Linux Mint too). Could you try the function `lasfilter`. This function call `stopifnotlas`. It is expected to fail on your computer. Does it?

**Comment by bi0m3trics** [comment]
For what it’s worth, I seem to recall getting this message when I had a mismatch between lidR and rlas… like when I updateed/installed lidR from GitHub but was using an older version of rlas from CRAN. I don’t make that mistake anymore. ;)
A dump from sessionInfo() might help too…

**Comment by Jean-Romain** [comment]
Great for you. I don't understand what happened. Hope this does not happen too often with other users...
