### ISSUE TITLE
R version problem

### ISSUE THREAD

**Issue by swinersha** [Jean-Romain/lidR#144]
I'm trying to install lidR on R versions 3.4.0, 3.4.3 and 3.4.4. I've tried using CRAN and through Github via devtools with no success. Which version of R do I need to install lidR at the moment? If lidR currently only works with older versions of R it would be helpful if you could make this information available in the readme so that people can get up and running quickly. 

Thanks

Tom

**Comment by Jean-Romain** [comment]
`lidR` works on all the R versions. 

### CRAN

At the time being `lidR` has been removed from the CRAN because of an issue with `rlas` that is all my bad :worried: . I expect to fix it within few days. I'm sorry.

### Github

You basically said me *it does not work*. That is not really helpful. It should work. What is going wrong?

**Comment by swinersha** [comment]
Yes. Sorry that was unclear.  Thanks for the rapid response.

I was getting the errors like "not possible to uninstall previous version of data.table" (not verbatim) and the same for Rcpp. 

I just updated my devtools to the version built under 3.4.4 and installed rlas and lidr with no problems. 

Thanks again.

**Comment by Jean-Romain** [comment]
> not possible to uninstall previous version of data.table

This is not related to `lidR` but to `Rcpp` and `data.table`. What if you install these packages manually

```r
install.packages(c("Rcpp", "data.table"))
```

**Comment by swinersha** [comment]
That might work. I have updated devtools now and everything worked fine so no problem as far as I'm concerned.
