### ISSUE TITLE
txt2las sugestion

### ISSUE THREAD

**Issue by GreKro** [Jean-Romain/lidR#173]
Hi Jean !

I have sugestion for creating new tool in lidR. Recently, I worked with data from terrestrial laser scanning, during the work I carried out the entire process in lidR with exception of conversion of files from xyz/txt to las files. Of corse there are many softwares provide this functionality like lastools (txt2las as open-source from liblas) CloudCompare (open-source) and probably more. But I thinik it would be great if that functionality will apear in lidR too.

**Comment by Jean-Romain** [comment]
Hi, 

Thank you for your suggestion. The short answer is that I won't implement such feature. But any pull request that implement a function is welcome.

The reasons I won't add such feature are:

1. as you mentioned there are already good open source tools to achieve this task. `txt2las` from `lastools` is open source and available on all platform.
2. `txt2las` is much much more efficient than any function we could add into `lidR` because it does not deal with the R overhead. 
3. `lidR` is not really a package to manipulate files. It is a package to process point clouds in a forestry context. The function `catalog_retile` is one of the exception because of the absence of open source equivalent.
4. I already have all the code to perform this task in the package `rlas` that relies on `laslib` the library that drives I/O in `lastools` but I disable the feature. I could rewrite an R version of `txt2las` but this would be nothing more than the already existing `txt2las` tools (in less good).
5. It is not really hard to create a basic function `readLASfromTXT`

```r
readLASfromTXT = function(file)
{
   data = data.table::fread(file)
   data.table::setname(data, new = c("X", "Y", "Z", "Intensity", ...))
   return(LAS(data))
}
```

However if you want to implement a robust function `readLASfromTXT` (that does a more robust job that the one above), feel free to make a PR :wink:

**Comment by GreKro** [comment]
Thanks for your answer. Now I have too little experience to be able to do it but maybe someday... Thanks for your tip with LAS function. Best regards ! :)
