### ISSUE TITLE
Issue with readLAS not opening .las files that used to open

### ISSUE THREAD

**Issue by BoilerF** [Jean-Romain/lidR#235]
Two days ago .las files that I had been able to work with started not being able to be read by readLAS. I have been receiving the following error message:

```
'Error in assert_all_are_existing_files(x) : File does not exist.'
```

Seeing that lidR was just recently extensively updated and R was updated to 3.5.3 a few days ago as well, I updated both the software and the package and am still receiving the same error message. Does anyone have any insight into why this may be? Are there new argument requirements for readLAS.

The syntax I am using that is no longer working is:

```r
object.name <- readLAS(file.path("file.location/file.las"))
```

Thank you for any assistance.

**Comment by Jean-Romain** [comment]
The function `readLAS` is tested probably several thousand of time per day so I'm pretty confident that there is not bug of that kind. Your error is very informative (file does not exist). Si if you really think it is a bug please provide a reproducible example otherwise if you need help to use the library please ask on https://gis.stackexchange.com/
