### ISSUE TITLE
is there a possibility of using PCL functions in R

### ISSUE THREAD

**Issue by muzo583** [Jean-Romain/lidR#237]
Hi all,

I wonder how can we use PCL (Point Cloud Library: [PCL](http://pointclouds.org/) ) commands in R. 

It would be very nice to use PCL power in R instead of try to write functions again. Is it possible? or What is the way of this library using in R?

Neither I am expert of R nor C++, unfortunately.

Thanks.

Mustafa

**Comment by Jean-Romain** [comment]
Well this is a very hard question actually.  The short answer is: yes it is possible but it will never happen in lidR.

-----------

PCL is a C++ library so everything is possible. I already built a package that relied on some PCL stuff. I deleted it several years ago but it still exists because somebody forked it https://github.com/jonvw28/lidRExtra

So for personal projects it is possible. But:

1. It is very hard to do even on Linux. It took me hours to figure out how to add the correct compilation directive in the makefile and yet it is an installation that is not generic https://github.com/jonvw28/lidRExtra/blob/master/src/Makevars#L2
2. PCL is terribly hard to install on Windows. I have never succeed myself and thus can't develop a package that rely on PCL (and I don't speak about Mac). So for me PCL it for Linux only.
3. I don't know how to build a package that rely on third party library and that is CRAN-valid. To build such a package the CRAN should have installed PCL on each of their server. Maintaining lidR is already an hard job that imply a lot of trouble, a PCL-based package is way to much to me.

So as a conclusion, yes but not with me.
