### ISSUE TITLE
export raster of CHM

### ISSUE THREAD

**Issue by cherrytree456** [Jean-Romain/lidR#262]
Hello-

I would like to use lidR to produce canopy height rasters. I was following along in your 'rasterizing perfect CHM' user guide and now I'm wondering what your suggestion would be for exporting this raster to a GeoTiff or .img. In particular, I think I'm going to loop through each tile and produce a CHM using this line of your code...
`chm6 = grid_canopy(las, 0.25, pitfree(c(0,2,5,10,15), c(0,1), subcircle = 0.2))`

Of course, I'll change the pixel size, etc. for my use case. 

Thanks for your suggestion.

**Comment by Jean-Romain** [comment]
If you have question about using the lidR package please ask on https://gis.stackexchange.com/ with the tag `lidr`. Me or somebody else will be able to help you and your question will benefit to other users. I no longer answer to question on github because it takes a lot of time and do not benefit to other users (github issues are poorly indexed by search engines). Please only report bug on github. Regards.
