### ISSUE TITLE
Exporting the results of segmentation

### ISSUE THREAD

**Issue by FalahIGT** [Jean-Romain/lidR#354]
Hey there 😄 
When i use your script on Rstudio the hulls that i export are quite "chubby" compared to the actual tree crowns ... do you happen to know a way to export the exact projection of the crowns that were delienated ( i believe the problem resides in the tree_hulls or delienate_crowns functions because when i exported the cloud it is very well segmented) 
Thank you so much in advance 😄

**Comment by Jean-Romain** [comment]
Dear @FalahIGT ,

This is a semi automatic message. I no longer answer to questions about lidR by email or on github because I receive too many questions from too many users. If you have questions about using the lidR package please ask on [gis.stackexchange.com](https://gis.stackexchange.com/) with the tag `lidr`. On stackexchange.com other users can also answer your questions and the answers thus provided will be public and well indexed by search engines so they can also help other users. Moreover we can provide link to already answered questions.

However you can still contact me (preferably on [github](https://github.com/Jean-Romain/lidR)) to report troubleshooting (with reproducible examples) or to ask for new features or anything that is not a "how to" question.

Also when asking on Stack Exchange pay attention at asking a clear, well documented, reproducible and focused questions. As is nobody can guess what you are trying to do and what is your problem.

Regards
