### ISSUE TITLE
No add_treetops3d plot window 

### ISSUE THREAD

**Issue by cyril06** [Jean-Romain/lidR#361]
Hello,
When a tree top object is cropped by an extent it is impossible to plot with `add_treetops3d()`.

```r
ttops <- tree_detection(ctg, lmf(5))
l <- readLAS(ctg[50,])
temp <- crop(ttops,extent(l))
x <- plot(l)
add_treetops3d(x, temp)
```

The plot window doesn't appear.

Am I doing something wrong ?

Regards

**Comment by Jean-Romain** [comment]
This is a little short to give you an answer. The code looks good. Are you sure that the window does not appear because the rendering is too long. How many points are they? what is the size of the tile? what is the point density? Have you tried with a smaller example? are you able to produce a reproducible example? Please provide details on your issue.

**Comment by cyril06** [comment]
When you launch the command:
add_treetops3d(x, ttops)
Everything is fine.

What is the real difference between ttops and temp ? Maybe there is a bug somewhere.

Regards

**Comment by Jean-Romain** [comment]
As I said without a reproducible example I can hardly help you. The following works:

```r
LASfile <- system.file("extdata", "Topography.laz", package="lidR")
las <- readLAS(LASfile)
temp <- find_trees(las, lmf(ws = 5))

x <= plot(las)
add_treetops3d(x, temp)
```

**Comment by cyril06** [comment]
Maybe there is something wrong like not enough memory. I'll try later when I have restarted my R session.

Now when I launch:
x=plot(l)
The plot window appears.

Regards
