### ISSUE TITLE
lidR error: object 'ORIGINALFILENAME' not found

### ISSUE THREAD

**Issue by cwadeross** [Jean-Romain/lidR#363]
I having a similar issue as #271 and have set chunk size to zero. 

```r
opt_chunk_size(ctg) = 0
outpath = "C:/my/out/dir/"
opt_output_files(ctg) <-  paste0(outpath, "/{*}")
# also throws error: paste0(outpath, "/{ORIGINALFILENAME}"
ctg_clip = clip_circle(ctg, xcenter=0.5, ycenter=0.5, radius=7.5)
```

Using something like "{ID}" works, but it does not output separate files.

**Comment by Jean-Romain** [comment]
No bug here but an error message that can be improved. Reproduced with 

```r
LASfile <- system.file("extdata", "Megaplot.laz", package="lidR")
ctg = readLAScatalog(LASfile)
opt_output_files(ctg) <-  paste0(tempdir(), "/{*}")
ctg_clip = clip_circle(ctg, xcenter=684850, ycenter=5017900, radius=7.5)
```

`opt_chunk_size(ctg) = 0` is meaningless here because we are not processing a wall-to-wall catalog by file, we are only extracting ROIs from a catalog. The documentation states

> chunk_size: Does not make sense here.

`{ORIGINALFILENAME}` is not an existing template for `clip_*()` for the same reason. You are not creating a new file that corresponds to the original one. The documentation states:

> The allowed templates in `clip_roi` are {XLEFT}, {XRIGHT}, {YBOTTOM}, {YTOP}, {ID}, {XCENTER}, {YCENTER} or any names from the table of attributes of a spatial object given as input such as {PLOT_ID} or {YEAR}, for example, if these attributes exist. If empty everything is returned into R.

The documentation could be clearer

The allowed templates in `clip_*` are {XLEFT}, {XRIGHT}, {YBOTTOM}, {YTOP}, {ID}, {XCENTER}, {YCENTER}. For `clip_roi` any name from the table of attributes of a spatial object given as input is also possible such as {PLOT_ID} or {YEAR}, for example, if these attributes exist. If empty everything is returned into R.

And the error could be improved for something like

> The template {ORIGINALFILENAME} makes sense only when processing by file. It is undefined in clip_* functions.

- [ ] update the doc of `clip_roi`
- [ ] add a more informative error.
