### ISSUE TITLE
Set classification with shapefile

### ISSUE THREAD

**Issue by DrThreeP** [Jean-Romain/lidR#381]
In v1x, I could could change the Classification using a shapefile using the following code:  

```r
myLasDat<- lasfilter(myLas,myShape,myFld)
```
This line fails after upgrading to lidR v3x. 

How can I manually set the Classification using a shpefile in the most recent version of lidR?

**Comment by Jean-Romain** [comment]
Hi,

1. [Version 2.0](https://github.com/Jean-Romain/lidR/releases/tag/v2.0.0) introduced a full compatibility break with v1.x. This was necessary (see the changelog) but it was 2 years ago when the package was not yet too widely used. If you just updated from 1.x, I'm sorry for you. Updating regularly your packages is not only a matter of new features but also of bug fixes (a lot).
2. `las_filter()` (now renamed `filter_poi()`) was never designed to support `Spatial*` object and was never designed to change any attribute. I don't understand what do you mean here. Please provide a minimal reproducible example.
3. This is a bug tracker. I no longer answer to questions about lidR on github because I receive too many questions from too many users. If you have questions about using the lidR package please ask on [gis.stackexchange.com](https://gis.stackexchange.com/) with the tag `lidr`. On stackexchange.com other users can also answer your questions and the answers thus provided will be public and well indexed by search engines so they can also help other users. Moreover we can provide link to already answered questions.

Regards
