### ISSUE TITLE
point_metrics not respecting set_lidr_threads

### ISSUE THREAD

**Issue by bi0m3trics** [Jean-Romain/lidR#382]
Hey JR,

I apologize if `point_metrics()` isn't mutlithreaded, but it seems to me that it should be (i.e., metrics should be able to be calculated for one point independently of another point) but when I run the following code I only see the point metrics being calculated using one thread...

```r
LASfile <- system.file("extdata", "MixedConifer.laz", package="lidR")
las = readLAS(LASfile)
temp1 = point_metrics(las, .stdshapemetrics, k = 30)

set_lidr_threads(4L)
temp2 = point_metrics(las, .stdshapemetrics, k = 30)
```

Am I missing something or is this a bug? Thanks!

**Comment by Jean-Romain** [comment]
All `*_metrics()` functions should be multi-threaded but they cannot be because they call user-defined R code and this is not thread safe. For example this would crash your R session

```r
temp1 = point_metrics(las, ~print(mean(Z)), k = 30)
```

Similarly if you abort the execution of the loop this may also crash your R session. For other multi-threaded functions I wrote thread-safe interruption but in `*_metrics()` functions the abortion might be checked within the user-defined R code in a child process. This is not thread safe and crashes because the R interpreter is single-threaded.
