### ISSUE TITLE
Big las tile creating pit free chm

### ISSUE THREAD

**Issue by Tobias1234** [Jean-Romain/lidR#416]
Hi. I have a big las tile 1.5*1.5 km2. I have a hard time normalizing las data and creating pit free chm. Using readlascatalog and chunks is cumbersome, seems I have to write the data in chunks and load them again? Thing is I want a seemless chm over a big area.

**Comment by Jean-Romain** [comment]
Hi. I no longer answer to questions about lidR by email or on github because I receive too many questions from too many users. If you have questions please ask on [gis.stackexchange.com](https://gis.stackexchange.com/) with the tag `lidr`. On stackexchange.com other users can also answer your questions and the answers thus provided will be public and well indexed by search engines so they can also help other users. Moreover we can provide link to already answered questions.

That being said, I can't see any question here. If you ask a question on [gis.stackexchange.com](https://gis.stackexchange.com/)  please clarify your request.

Regards
