### ISSUE TITLE
Calculating number of points per voxel summed over z-axis? vm <- voxel_metrics(las, ~length(Z), res)?

### ISSUE THREAD

**Issue by mavavilj** [Jean-Romain/lidR#429]
I'm trying to calculate the total number of points per x-y voxel summed along axis z.

I read the code:

https://github.com/Jean-Romain/lidR/blob/4612963e6f73ead5840715434f55eaa46ec5ce24/R/voxel_metrics.R#L59

And this seemed promising, but I didn't understand how `~length(Z)` behaves. Based on the example https://github.com/Jean-Romain/lidR/blob/4612963e6f73ead5840715434f55eaa46ec5ce24/R/voxel_metrics.R#L67

it would seem that for each voxel it calculates "length(Z)", but what's this? It says 

> in each voxel the number of points is computed.

but how does `(Z)` refer to this?

How do I realize a sum over "z-pillars"? Or perhaps I must do that on the returned object?

**Comment by Jean-Romain** [comment]
Dear user of the lidR package,

This is a semi automatic message. I no longer answer to questions about lidR by email or on github because I receive too many questions from too many users. If you have questions about using the lidR package please ask on [gis.stackexchange.com](https://gis.stackexchange.com/) with the tag `lidr`. On stackexchange.com other users can also answer your questions and the answers thus provided will be public and well indexed by search engines so they can also help other users. Moreover we can provide link to already answered questions.

However you can still contact me (preferably on [github](https://github.com/Jean-Romain/lidR)) to report troubleshooting (with reproducible examples) or to ask for new features or anything that is not a "how to" question.

Regards
