### ISSUE TITLE
Drag zoomed in LiDAR data in RGL window

### ISSUE THREAD

**Issue by Saadi4469** [Jean-Romain/lidR#442]
In some softwares the user can hold down the middle mouse button to drag the visual data. How can this be done while correcting the tree tops identified in a zoomed in view?

`TTops.manual = find_trees(LAS_denoised, manual(LAS_TTops)) `

**Comment by Jean-Romain** [comment]
Good question. I did not use this function for years but if I remember well you identify the trees with the right button, and the right button is also associated to the drag event. So, I guess drag action is overwritten by the selection action. The reason is that `manual()` was existing before the 3D rendering in lidR supports the drag action.

I guess I could put the selection with the middle button to keep the drag action.

**Comment by Jean-Romain** [comment]
Which version of the package are you using ? It seems that the function no longer works...

**Comment by Jean-Romain** [comment]
I fixed the error. I'd like to know which version of `lidR` and `rgl` were in use on your computer because the bug I experienced was not existing before and I did not change the function for years. So I suspect an slight modification in `rgl` itself.

Also the default button for selection is now the middle button. This automatically enabled the right button that is the default for panning in lidR.

Thank for reporting

**Comment by Saadi4469** [comment]
I am using the latest version of lidR  ver. 3.1.3 and rgl ver. 0.106.8 available on CRAN. And I still have to use the right mouse button to add or flag tree tops, and the middle mouse button stretches the view.

**Comment by Jean-Romain** [comment]
Yes of course. You must install the latest version from github. It is not yet on CRAN

**Comment by Saadi4469** [comment]
for both lidR and rgl, or just lidR?

**Comment by Jean-Romain** [comment]
Just `lidR`.This is the only source code I can update. I've no control on `rgl`.

**Comment by Saadi4469** [comment]
Yes, the drag function works now thank you and cheers on fixing the error.
