### ISSUE TITLE
[bug] lastree method "li2012" provide EMPTY output 

### ISSUE THREAD

**Issue by spono** [Jean-Romain/lidR#55]
lasground-> grid_terrain-> lasnormalize-> lasfilterfirst-> lastree-> empty output.
Tested the tool from 1.2.0.900 version on three different machines with Windows 10 64bit .

**Comment by Jean-Romain** [comment]
Hi,

Than you for reporting this bug. Did you test with the data given as example? It should work. If it doesn't I'll investigate. If the method works with the data given as example but not with yours I will need a sample of your data which enable to reproduce the bug. Otherwise I'll not be able to find the bug.

Thank you

**Comment by Jean-Romain** [comment]
Mmm forgot my previous message, actually I think this is not a bug, its a feature. The default behavior of `lastrees` is to return nothing and update your original dataset by reference. Please refer to the doc. For the two other algorithms when `extra = true` you can get an optional output but this is not the default behavior.
